name: 'Hello World'
description: 'testing'
inputs:
  foo:
    description: 'Fooey'
    required: true
    default: 'Foo'
outputs:
  bar:
    description: 'Bar'
    value: ${{ steps.foo-bar.outputs.bar }}
runs:
  using: 'composite'
  steps:
    - run: echo ${{ inputs.foo }}
      shell: bash
    - id: foo-bar
      run: |
        git remote set-url origin git@github.com:MarvJohnson/composit-action.git
        git config user.name 'Github Action'
        git config user.email '<>'
        git commit --allow-empty -m 'Testing'
        git push origin main
      shell: bash
