name: 'Extension Publisher'
description: 'Creates a release/x.x.x branch, updates version numbers for package/package-lock, commits and pushes, and makes PR into main'
inputs:
  version:
    description: 'The version this extension will change to.'
    required: true
runs:
  using: 'composite'
  steps:
    - shell: bash
      run: |
        git config user.name 'Github Action'
        git config user.email '<>'
        git checkout -b release/${{ inputs.version }}
        npm i
        npm --no-git-tag-version -f version ${{ inputs.version }}
        git add .
        git commit -m 'Preparing ${{ inputs.version }} Release'
        git push origin main
        gh pr create --fill
