name: 'Hello World'
description: 'testing'
inputs:
  foo:
    description: 'Fooey'
    required: true
    default: 'Foo'
outputs:
  bar:
    description: 'Bar'
    value: ${{ steps.foo-bar.outputs.bar }}
jobs:
  test:
    runs-on: 'composite'
    steps:
      - run: echo ${{ inputs.foo }}
        shell: bash
      - id: foo-bar
        run: echo "::set-output name=bar::$(echo hello)"
        shell: bash
  test2:
    runs-on: 'node12'
    steps:
      - runs: |
          node console.log('hello world');
        
