name: 'Extension Publisher'
description: 'Creates a release/x.x.x branch, updates version numbers for package/package-lock, commits and pushes, and makes PR into main'
inputs:
  new_version:
    description: 'The version this extension will change to.'
    required: true
runs:
  using: 'composite'
  steps:
    env:
      PACKAGE_NAME: ${{ node -p "require('./package.json').name" }}
    - shell: bash
      run: |
        echo "$PACKAGE_NAME"
        git config user.name 'Github Action'
        git config user.email '<>'
        git checkout -b release/${{ inputs.new_version }}
        npm --no-git-tag-version version ${{ inputs.new_version }}
        git add .
        git commit -m "Preparing ${{ inputs.new_version }} Release"
        git push origin release/${{ inputs.new_version }}
        gh pr create --title "Prepare ${{ inputs.new_version }} Release" --body ''
