name: 'Extension Publisher'

on:
  workflow_call:
    inputs:
      new_version:
        type: string
        required: true

jobs:
  setup:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 14
      - shell: bash
        name: configure_git
        run: |
          git config user.name 'Github Action'
          git config user.email '<>'
          git checkout -b release/${{ inputs.new_version }}
          npm --no-git-tag-version version ${{ inputs.new_version }}
          git add .
          git commit -m "Preparing ${{ inputs.new_version }} Release"
          git push origin release/${{ inputs.new_version }}
          gh pr create --title "Prepare ${{ inputs.new_version }} Release" --body ''
      - shell: bash
        name: update_version
        run: |
          echo "updated_version=$(node -p "require('./package.json').version")" >> $GITHUB_ENV
          echo $UPDATED_VERSION
      
