name: 'Extension Publisher'
description: 'Creates a release/x.x.x branch, updates version numbers for package/package-lock, commits and pushes, and makes PR into main'
inputs:
  new_version:
    description: 'The version this extension will change to.'
    required: true
jobs:
  prepare_release:
    runs-on: ubuntu-latest
    uses: actions/checkout@v2
    uses: actions/setup-node@v3
    with:
      node-version: 14
    steps:
      - shell: bash
        run: echo "hello world"
